title: Ben Smithgall's site
description: |
  Bit pusher at Spotify. Previously Interactive News at the New York Times, 
  U.S. Digital Service, and Code for America.
url: https://bensmithgall.com
markdown: kramdown
permalink: /:categories/:title
baseurl: /
rdiscount extensions: [smart]
paginate: 5
future: false
highlighter: rouge
plugins: [jekyll-paginate]
